#stage 1 building

FROM node:14-slim as builder
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build

#stage 2 serving

FROM node:14-slim 
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install --production
COPY --from=builder /usr/src/app/build ./build
COPY .env .
EXPOSE 5000
CMD ["npm", "run", "serve"]
